// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace corSeguros.Models;

public partial class Anio
{
    public int IdAnio { get; set; }

    public int Año { get; set; }

    public virtual ICollection<Versione> Versiones { get; set; } = new List<Versione>();
}