// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace corSeguros.Models;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public string Apellido { get; set; }

    public string Nombre { get; set; }

    public string Telefono { get; set; }

    public string Mail { get; set; }

    public virtual ICollection<Cotizacione> Cotizaciones { get; set; } = new List<Cotizacione>();
}