// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace corSeguros.Models;

public partial class Cobertura
{
    public int IdCobertura { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<DetallesSeguro> DetallesSeguros { get; set; } = new List<DetallesSeguro>();
}