// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace corSeguros.Models;

public partial class CodigosPostale
{
    public int IdCodPostal { get; set; }

    public int? IdBarrio { get; set; }

    public int Numero { get; set; }

    public virtual ICollection<Cotizacione> Cotizaciones { get; set; } = new List<Cotizacione>();

    public virtual Barrio IdBarrioNavigation { get; set; }

    public virtual ICollection<ZonasRiesgo> ZonasRiesgos { get; set; } = new List<ZonasRiesgo>();
}