// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace corSeguros.Models;

public partial class Cotizacione
{
    public int IdCotizacion { get; set; }

    public int? IdCliente { get; set; }

    public DateTime FechaEmision { get; set; }

    public DateTime FechaVenc { get; set; }

    public int? IdCodPostal { get; set; }

    public int? IdSeguro { get; set; }

    public decimal Precio { get; set; }

    public bool Aprobada { get; set; }

    public int? IdSucursal { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual CodigosPostale IdCodPostalNavigation { get; set; }

    public virtual Seguro IdSeguroNavigation { get; set; }

    public virtual Sucursale IdSucursalNavigation { get; set; }
}