// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace corSeguros.Models;

public partial class DetallesSeguro
{
    public int IdDetalle { get; set; }

    public int? IdSeguro { get; set; }

    public int? IdCobertura { get; set; }

    public virtual Cobertura IdCoberturaNavigation { get; set; }

    public virtual Seguro IdSeguroNavigation { get; set; }
}