// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace corSeguros.Models;

public partial class Marca
{
    public int IdMarca { get; set; }

    public string Nombre { get; set; }

    public int? IdTipo { get; set; }

    public virtual TiposVehiculo IdTipoNavigation { get; set; }

    public virtual ICollection<Modelo> Modelos { get; set; } = new List<Modelo>();
}