// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace corSeguros.Models;

public partial class Modelo
{
    public int IdModelo { get; set; }

    public string Nombre { get; set; }

    public int? IdMarca { get; set; }

    public virtual Marca IdMarcaNavigation { get; set; }

    public virtual ICollection<Versione> Versiones { get; set; } = new List<Versione>();
}