// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace corSeguros.Models;

public partial class NivelesRiesgo
{
    public int IdNivel { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<ZonasRiesgo> ZonasRiesgos { get; set; } = new List<ZonasRiesgo>();
}