// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace corSeguros.Models;

public partial class Provincia
{
    public int IdProvincia { get; set; }

    public string NombreProvincia { get; set; }

    public virtual ICollection<Localidade> Localidades { get; set; } = new List<Localidade>();
}