// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace corSeguros.Models;

public partial class Seguro
{
    public int IdSeguro { get; set; }

    public int? IdTipoSeg { get; set; }

    public int? IdVersion { get; set; }

    public decimal Precio { get; set; }

    public virtual ICollection<Cotizacione> Cotizaciones { get; set; } = new List<Cotizacione>();

    public virtual ICollection<DetallesSeguro> DetallesSeguros { get; set; } = new List<DetallesSeguro>();

    public virtual TiposSeguro IdTipoSegNavigation { get; set; }

    public virtual Versione IdVersionNavigation { get; set; }
}