// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace corSeguros.Models;

public partial class Sucursale
{
    public int IdSucursal { get; set; }

    public string Direccion { get; set; }

    public int IdLocalidad { get; set; }

    public virtual ICollection<Cotizacione> Cotizaciones { get; set; } = new List<Cotizacione>();

    public virtual Localidade IdLocalidadNavigation { get; set; }
}