// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace corSeguros.Models;

public partial class Versione
{
    public int IdVersion { get; set; }

    public string Descripcion { get; set; }

    public int? IdModelo { get; set; }

    public int? IdAnio { get; set; }

    public virtual Anio IdAnioNavigation { get; set; }

    public virtual Modelo IdModeloNavigation { get; set; }

    public virtual ICollection<Seguro> Seguros { get; set; } = new List<Seguro>();
}