// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace corSeguros.Models;

public partial class ZonasRiesgo
{
    public int IdZona { get; set; }

    public int? IdNivel { get; set; }

    public int? IdCodPostal { get; set; }

    public virtual CodigosPostale IdCodPostalNavigation { get; set; }

    public virtual NivelesRiesgo IdNivelNavigation { get; set; }
}